// GENERATED by tools/stores/build_logos.py from Simple Icons 16.31.0 (CC0). Do not edit by hand.
package com.cikup.amazgone.stores.presentation

import amazgone.shared.generated.resources.Res
import amazgone.shared.generated.resources.logo_apple
import amazgone.shared.generated.resources.logo_asus
import amazgone.shared.generated.resources.logo_beats
import amazgone.shared.generated.resources.logo_chrysler
import amazgone.shared.generated.resources.logo_dell
import amazgone.shared.generated.resources.logo_dior
import amazgone.shared.generated.resources.logo_epicgames
import amazgone.shared.generated.resources.logo_gogdotcom
import amazgone.shared.generated.resources.logo_google
import amazgone.shared.generated.resources.logo_huawei
import amazgone.shared.generated.resources.logo_humblebundle
import amazgone.shared.generated.resources.logo_lenovo
import amazgone.shared.generated.resources.logo_nike
import amazgone.shared.generated.resources.logo_oppo
import amazgone.shared.generated.resources.logo_puma
import amazgone.shared.generated.resources.logo_samsung
import amazgone.shared.generated.resources.logo_steam
import amazgone.shared.generated.resources.logo_ubisoft
import amazgone.shared.generated.resources.logo_vivo
import androidx.compose.ui.graphics.Color
import org.jetbrains.compose.resources.DrawableResource

/** A brand's mark (white glyph, null = use a monogram) on its official colour. */
data class BrandLogo(val glyph: DrawableResource?, val color: Color)

/** Store id -> logo. Brand colours are identity data, so they live here rather than in the theme. */
internal val BRAND_LOGOS: Map<String, BrandLogo> = mapOf(
    "digital-1" to BrandLogo(Res.drawable.logo_steam, Color(0xFF000000)),
    "digital-11" to BrandLogo(Res.drawable.logo_humblebundle, Color(0xFFCC2929)),
    "digital-13" to BrandLogo(Res.drawable.logo_ubisoft, Color(0xFF000000)),
    "digital-25" to BrandLogo(Res.drawable.logo_epicgames, Color(0xFF313131)),
    "digital-7" to BrandLogo(Res.drawable.logo_gogdotcom, Color(0xFF86328A)),
    "official-apple" to BrandLogo(Res.drawable.logo_apple, Color(0xFF000000)),
    "official-asus" to BrandLogo(Res.drawable.logo_asus, Color(0xFF000000)),
    "official-beats" to BrandLogo(Res.drawable.logo_beats, Color(0xFF005571)),
    "official-chrysler" to BrandLogo(Res.drawable.logo_chrysler, Color(0xFF000000)),
    "official-dell" to BrandLogo(Res.drawable.logo_dell, Color(0xFF007DB8)),
    "official-dior" to BrandLogo(Res.drawable.logo_dior, Color(0xFF000000)),
    "official-google" to BrandLogo(Res.drawable.logo_google, Color(0xFF4285F4)),
    "official-huawei" to BrandLogo(Res.drawable.logo_huawei, Color(0xFFFF0000)),
    "official-lenovo" to BrandLogo(Res.drawable.logo_lenovo, Color(0xFFE2231A)),
    "official-nike" to BrandLogo(Res.drawable.logo_nike, Color(0xFF111111)),
    "official-oppo" to BrandLogo(Res.drawable.logo_oppo, Color(0xFF2D683D)),
    "official-puma" to BrandLogo(Res.drawable.logo_puma, Color(0xFF242B2F)),
    "official-samsung" to BrandLogo(Res.drawable.logo_samsung, Color(0xFF1428A0)),
    "official-vivo" to BrandLogo(Res.drawable.logo_vivo, Color(0xFF415FFF)),
    "digital-15" to BrandLogo(null, Color(0xFFFF6A00)),
    "digital-2" to BrandLogo(null, Color(0xFF1F2A44)),
    "digital-21" to BrandLogo(null, Color(0xFF0072BC)),
    "digital-23" to BrandLogo(null, Color(0xFFE4002B)),
    "digital-27" to BrandLogo(null, Color(0xFFE30613)),
    "digital-28" to BrandLogo(null, Color(0xFFE2001A)),
    "digital-3" to BrandLogo(null, Color(0xFF00A651)),
    "digital-30" to BrandLogo(null, Color(0xFFD32E2E)),
    "digital-35" to BrandLogo(null, Color(0xFF6C2BD9)),
    "official-amazon" to BrandLogo(null, Color(0xFFFF9900)),
    "official-annibale-colombo" to BrandLogo(null, Color(0xFF6B4E31)),
    "official-calvin-klein" to BrandLogo(null, Color(0xFF000000)),
    "official-chanel" to BrandLogo(null, Color(0xFF000000)),
    "official-dodge" to BrandLogo(null, Color(0xFFC8102E)),
    "official-dolce-gabbana" to BrandLogo(null, Color(0xFF000000)),
    "official-essence" to BrandLogo(null, Color(0xFFE4007C)),
    "official-gigabyte" to BrandLogo(null, Color(0xFF003A70)),
    "official-gucci" to BrandLogo(null, Color(0xFF1B4332)),
    "official-iwc" to BrandLogo(null, Color(0xFF1B1B1B)),
    "official-kawasaki" to BrandLogo(null, Color(0xFF66CC33)),
    "official-knoll" to BrandLogo(null, Color(0xFFC8102E)),
    "official-longines" to BrandLogo(null, Color(0xFF1D3E6B)),
    "official-off-white" to BrandLogo(null, Color(0xFF1A1A1A)),
    "official-olay" to BrandLogo(null, Color(0xFF8B1538)),
    "official-prada" to BrandLogo(null, Color(0xFF000000)),
    "official-realme" to BrandLogo(null, Color(0xFFFFC915)),
    "official-rolex" to BrandLogo(null, Color(0xFF006039)),
    "official-vaseline" to BrandLogo(null, Color(0xFF00539B)),
)
