package com.cikup.amazgone.core.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

// GENERATED by tools/theme/generate_colors.py (Material Color Utilities, Fidelity variant):
// seed orange #FF6B2C → primary (primaryContainer keeps the exact brand orange), navy #1E1B3A → secondary/neutrals.
// The only file allowed to contain raw colors.

internal val LightColorScheme: ColorScheme = lightColorScheme(
    primary = Color(0xFFA83900),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFF6B2C),
    onPrimaryContainer = Color(0xFF5C1C00),
    secondary = Color(0xFF5D5791),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFC3BCFD),
    onSecondaryContainer = Color(0xFF4F4A82),
    tertiary = Color(0xFF7E5700),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFC98E12),
    onTertiaryContainer = Color(0xFF442D00),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFCF8FD),
    onBackground = Color(0xFF1C1B1F),
    surface = Color(0xFFFCF8FD),
    onSurface = Color(0xFF1C1B1F),
    surfaceVariant = Color(0xFFE5E1EC),
    onSurfaceVariant = Color(0xFF47464F),
    outline = Color(0xFF787680),
    outlineVariant = Color(0xFFC9C5D0),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF313034),
    inverseOnSurface = Color(0xFFF4EFF4),
    inversePrimary = Color(0xFFFFB59A),
    surfaceDim = Color(0xFFDDD9DD),
    surfaceBright = Color(0xFFFCF8FD),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF7F2F7),
    surfaceContainer = Color(0xFFF1ECF1),
    surfaceContainerHigh = Color(0xFFEBE7EC),
    surfaceContainerHighest = Color(0xFFE5E1E6),
)

internal val DarkColorScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFFFFB59A),
    onPrimary = Color(0xFF5B1B00),
    primaryContainer = Color(0xFFFF6B2C),
    onPrimaryContainer = Color(0xFF5C1C00),
    secondary = Color(0xFFC6BFFF),
    onSecondary = Color(0xFF2E295F),
    secondaryContainer = Color(0xFF47427A),
    onSecondaryContainer = Color(0xFFB8B1F1),
    tertiary = Color(0xFFFDBB43),
    onTertiary = Color(0xFF432C00),
    tertiaryContainer = Color(0xFFC98E12),
    onTertiaryContainer = Color(0xFF442D00),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF141316),
    onBackground = Color(0xFFE5E1E6),
    surface = Color(0xFF141316),
    onSurface = Color(0xFFE5E1E6),
    surfaceVariant = Color(0xFF47464F),
    onSurfaceVariant = Color(0xFFC9C5D0),
    outline = Color(0xFF928F99),
    outlineVariant = Color(0xFF47464F),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE5E1E6),
    inverseOnSurface = Color(0xFF313034),
    inversePrimary = Color(0xFFA83900),
    surfaceDim = Color(0xFF141316),
    surfaceBright = Color(0xFF3A383C),
    surfaceContainerLowest = Color(0xFF0E0E11),
    surfaceContainerLow = Color(0xFF1C1B1F),
    surfaceContainer = Color(0xFF201F23),
    surfaceContainerHigh = Color(0xFF2A292D),
    surfaceContainerHighest = Color(0xFF353438),
)

/** Content drawn over the always-dark image scrim (hero captions); identical in light and dark themes. */
val OnScrimColor: Color = Color(0xFFFFFFFF)

/**
 * M3 "extended colors" for brand surfaces the standard roles don't cover
 * (read via `AmazgoneTheme.extended`).
 */
@Immutable
data class ExtendedColors(
    /** Floating navigation bar, flash-sale banners. Deep navy in both themes. */
    val brandNavy: Color,
    val onBrandNavy: Color,
    val onBrandNavyVariant: Color,
    /** Vivid call-to-action orange (buttons, selected nav pill, prices). */
    val cta: Color,
    val onCta: Color,
    /** Soft pastel tiles behind quick actions. */
    val tileTints: List<Color>,
)

internal val LightExtendedColors = ExtendedColors(
    brandNavy = Color(0xFF1E1B3A),
    onBrandNavy = Color(0xFFFFFFFF),
    onBrandNavyVariant = Color(0xFFB9B5D6),
    cta = Color(0xFFFF6B2C),
    onCta = Color(0xFFFFFFFF),
    tileTints = listOf(Color(0xFFE8F1FF), Color(0xFFFFEFE6), Color(0xFFE9F8EF), Color(0xFFF3ECFF), Color(0xFFFFF6DB)),
)

internal val DarkExtendedColors = LightExtendedColors.copy(
    brandNavy = Color(0xFF2A2650),
    tileTints = listOf(Color(0xFF1F2B3D), Color(0xFF3A2519), Color(0xFF1C3226), Color(0xFF2B2240), Color(0xFF363018)),
)

val LocalExtendedColors = staticCompositionLocalOf { LightExtendedColors }
