package com.cikup.amazgone.core.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

// GENERATED by tools/theme/generate_colors.py (Material Color Utilities, Fidelity variant + brand overrides):
// primary = exact brand orange #FF6B2C, secondary = calm navy-grey, grey page + white cards.
// The only file allowed to contain raw colors. Regenerate instead of hand-editing.

internal val LightColorScheme: ColorScheme = lightColorScheme(
    primary = Color(0xFFFF6B2C),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFE3D6),
    onPrimaryContainer = Color(0xFF5C1C00),
    secondary = Color(0xFF5F5C6E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEDEBF3),
    onSecondaryContainer = Color(0xFF1E1B3A),
    tertiary = Color(0xFFB77A00),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFE7B0),
    onTertiaryContainer = Color(0xFF4A3000),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF5F5F8),
    onBackground = Color(0xFF1C1B1F),
    surface = Color(0xFFF5F5F8),
    onSurface = Color(0xFF1C1B1F),
    surfaceVariant = Color(0xFFE5E1EC),
    onSurfaceVariant = Color(0xFF47464F),
    outline = Color(0xFF787680),
    outlineVariant = Color(0xFFC9C5D0),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF313034),
    inverseOnSurface = Color(0xFFF4EFF4),
    inversePrimary = Color(0xFFFFB59A),
    surfaceDim = Color(0xFFE4E3E8),
    surfaceBright = Color(0xFFF5F5F8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFFFFF),
    surfaceContainer = Color(0xFFEFEEF3),
    surfaceContainerHigh = Color(0xFFEAE9EF),
    surfaceContainerHighest = Color(0xFFE3E2E8),
)

internal val DarkColorScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFFFF7A3F),
    onPrimary = Color(0xFF2A0C00),
    primaryContainer = Color(0xFF6B2A0B),
    onPrimaryContainer = Color(0xFFFFDBCC),
    secondary = Color(0xFFC8C4D9),
    onSecondary = Color(0xFF302F3F),
    secondaryContainer = Color(0xFF2E2C38),
    onSecondaryContainer = Color(0xFFE6E3F2),
    tertiary = Color(0xFFFFC04D),
    onTertiary = Color(0xFF3D2800),
    tertiaryContainer = Color(0xFF5A3F00),
    onTertiaryContainer = Color(0xFFFFE7B0),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF121116),
    onBackground = Color(0xFFE5E1E6),
    surface = Color(0xFF121116),
    onSurface = Color(0xFFE5E1E6),
    surfaceVariant = Color(0xFF47464F),
    onSurfaceVariant = Color(0xFFC9C5D0),
    outline = Color(0xFF928F99),
    outlineVariant = Color(0xFF47464F),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE5E1E6),
    inverseOnSurface = Color(0xFF313034),
    inversePrimary = Color(0xFFA83900),
    surfaceDim = Color(0xFF141316),
    surfaceBright = Color(0xFF3A383C),
    surfaceContainerLowest = Color(0xFF1D1C22),
    surfaceContainerLow = Color(0xFF1D1C22),
    surfaceContainer = Color(0xFF232228),
    surfaceContainerHigh = Color(0xFF2B2A30),
    surfaceContainerHighest = Color(0xFF35343A),
)

/** Content drawn over the always-dark image scrim (hero captions); identical in light and dark themes. */
val OnScrimColor: Color = Color(0xFFFFFFFF)

/**
 * M3 "extended colors" for brand surfaces the standard roles don't cover
 * (read via `AmazgoneTheme.extended`).
 */
@Immutable
data class ExtendedColors(
    /** Floating navigation bar, flash-sale banners. Deep navy in both themes. */
    val brandNavy: Color,
    val onBrandNavy: Color,
    val onBrandNavyVariant: Color,
    /** Vivid call-to-action orange (buttons, selected nav pill, prices). */
    val cta: Color,
    val onCta: Color,
    /** Positive status (in stock, verified purchase). */
    val success: Color,
    /** Backdrop for product photos (shot on white): stays white in dark mode too, like big shops do. */
    val imageStage: Color,
    /** Soft pastel tiles behind quick actions. */
    val tileTints: List<Color>,
)

internal val LightExtendedColors = ExtendedColors(
    brandNavy = Color(0xFF1E1B3A),
    onBrandNavy = Color(0xFFFFFFFF),
    onBrandNavyVariant = Color(0xFFB9B5D6),
    cta = Color(0xFFFF6B2C),
    onCta = Color(0xFFFFFFFF),
    success = Color(0xFF1E8E4F),
    imageStage = Color(0xFFFFFFFF),
    tileTints = listOf(Color(0xFFE8F1FF), Color(0xFFFFEFE6), Color(0xFFE9F8EF), Color(0xFFF3ECFF), Color(0xFFFFF6DB)),
)

internal val DarkExtendedColors = LightExtendedColors.copy(
    brandNavy = Color(0xFF2A2650),
    success = Color(0xFF5FD18E),
    tileTints = listOf(Color(0xFF1F2B3D), Color(0xFF3A2519), Color(0xFF1C3226), Color(0xFF2B2240), Color(0xFF363018)),
)

val LocalExtendedColors = staticCompositionLocalOf { LightExtendedColors }
