#!/usr/bin/env python3
"""Generate bundled store logos from Simple Icons (CC0, https://simpleicons.org).

Downloads the SVG of every brand we have a store for, converts it to a Compose/Android vector
drawable (composeResources/drawable/logo_<slug>.xml) and writes BrandLogos.kt mapping store id ->
drawable + official brand colour. Brands missing from Simple Icons fall back to a monogram in the
curated colour below. Re-run after changing the maps:  python3 tools/stores/build_logos.py
Logos are the brands' trademarks; the app shows them only to identify who sells a product.
"""
import json
import os
import re
import urllib.request

VERSION = "16.31.0"
CDN = f"https://cdn.jsdelivr.net/npm/simple-icons@{VERSION}"
ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
DRAWABLE = os.path.join(ROOT, "shared/src/commonMain/composeResources/drawable")
KOTLIN = os.path.join(ROOT, "shared/src/commonMain/kotlin/com/cikup/amazgone/stores/presentation/BrandLogos.kt")

# store id -> Simple Icons slug
LOGOS = {
    "official-apple": "apple", "official-samsung": "samsung", "official-google": "google", "official-oppo": "oppo",
    "official-vivo": "vivo", "official-huawei": "huawei", "official-asus": "asus", "official-lenovo": "lenovo",
    "official-dell": "dell", "official-beats": "beats", "official-nike": "nike", "official-puma": "puma",
    "official-dior": "dior", "official-chrysler": "chrysler",
    "digital-1": "steam", "digital-7": "gogdotcom", "digital-11": "humblebundle", "digital-13": "ubisoft", "digital-25": "epicgames",
}

# Real brand colours for stores without a Simple Icons logo (monogram fallback).
FALLBACK_COLORS = {
    "official-realme": "FFC915", "official-gigabyte": "003A70", "official-amazon": "FF9900", "official-rolex": "006039",
    "official-longines": "1D3E6B", "official-iwc": "1B1B1B", "official-calvin-klein": "000000", "official-off-white": "1A1A1A",
    "official-chanel": "000000", "official-dolce-gabbana": "000000", "official-gucci": "1B4332", "official-prada": "000000",
    "official-essence": "E4007C", "official-olay": "8B1538", "official-vaseline": "00539B", "official-knoll": "C8102E",
    "official-annibale-colombo": "6B4E31", "official-dodge": "C8102E", "official-kawasaki": "66CC33",
    "digital-2": "1F2A44", "digital-3": "00A651", "digital-15": "FF6A00", "digital-21": "0072BC", "digital-23": "E4002B",
    "digital-27": "E30613", "digital-28": "E2001A", "digital-30": "D32E2E", "digital-35": "6C2BD9",
}


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "AmazgoneLogoBuilder/1.0"})
    with urllib.request.urlopen(request) as response:
        return response.read().decode()


def main():
    data = json.loads(fetch(f"{CDN}/data/simple-icons.json"))
    icons = data if isinstance(data, list) else data["icons"]
    colors = {(i.get("slug") or ""): i["hex"] for i in icons}
    os.makedirs(DRAWABLE, exist_ok=True)
    entries = []
    for store_id, slug in sorted(LOGOS.items()):
        svg = fetch(f"{CDN}/icons/{slug}.svg")
        path = re.search(r'<path d="([^"]+)"', svg).group(1)
        name = "logo_" + slug.replace("-", "_")
        with open(os.path.join(DRAWABLE, name + ".xml"), "w") as f:
            f.write(
                '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
                '    android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">\n'
                f'    <path android:fillColor="#FFFFFFFF" android:pathData="{path}"/>\n'
                "</vector>\n"
            )
        entries.append((store_id, f"Res.drawable.{name}", colors.get(slug, "000000")))
    for store_id, hex_color in sorted(FALLBACK_COLORS.items()):
        entries.append((store_id, "null", hex_color))
    write_kotlin(entries)
    print(f"{len(LOGOS)} logos, {len(FALLBACK_COLORS)} colour-only brands")


def write_kotlin(entries):
    imports = sorted({e[1].split(".")[-1] for e in entries if e[1] != "null"})
    lines = [
        "// GENERATED by tools/stores/build_logos.py from Simple Icons " + VERSION + " (CC0). Do not edit by hand.",
        "package com.cikup.amazgone.stores.presentation",
        "",
        "import amazgone.shared.generated.resources.Res",
        *[f"import amazgone.shared.generated.resources.{i}" for i in imports],
        "import androidx.compose.ui.graphics.Color",
        "import org.jetbrains.compose.resources.DrawableResource",
        "",
        "/** A brand's mark (white glyph, null = use a monogram) on its official colour. */",
        "data class BrandLogo(val glyph: DrawableResource?, val color: Color)",
        "",
        "/** Store id -> logo. Brand colours are identity data, so they live here rather than in the theme. */",
        "internal val BRAND_LOGOS: Map<String, BrandLogo> = mapOf(",
        *[f'    "{sid}" to BrandLogo({res}, Color(0xFF{hx.upper()})),' for sid, res, hx in entries],
        ")",
        "",
    ]
    with open(KOTLIN, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
